### ISSUE TITLE
Table 17.1 Special cases of generalized beta

### ISSUE THREAD

**Issue by azev77** [gecrooks/fieldguide#1]
Since Pert is a special case of Beta, and Beta is a special case of Generalized Beta, then shouldn't Pert also be in Table 17.1?

**Comment by gecrooks** [comment]
A fair point.

**Comment by azev77** [comment]
Btw, you may wanna checkout the Julia package [Distributions](https://github.com/JuliaStats/Distributions.jl).jl. 
They are [working on adding distributions ](https://github.com/JuliaStats/Distributions.jl/issues/124)& prefer saving code when possible. Your Field Guide can be a game changer!
