### ISSUE TITLE
Wrong sign for generalized Gumbel

### ISSUE THREAD

**Issue by jaburgoyne** [gecrooks/fieldguide#13]
I believe that the sign is incorrect in the parameterisation linking the generalized Gumbel distribution to its parent gamma-exponential distribution (8.4). Should it not be: GenGumbel(x; u, λ, n) = GammaExp(x; u **+** λ \ln n, λ, ν)? Version 1.0.0 of the field guide has a minus sign.

**Comment by gecrooks** [comment]
You're correct. Good catch.
