### ISSUE TITLE
GenBetaPrime

### ISSUE THREAD

**Issue by azev77** [gecrooks/fieldguide#3]
p. 124 it says:
`Dagum(gamma, beta) = GenBetaPrime(a,s,1,gamma,-beta)`
But `Dagum` only depends on two parameters (gamma,beta), not also on (a,s).

`LogLogistic(a,s,beta) = GenBetaPrime(0,s,1,1,beta)`
 But `LogLogistic` only depends on 3 parameters (a,s,beta), but `GenBetaPrime` is missing `a`.

Also, the [Kumaraswamy distribution](https://en.wikipedia.org/wiki/Kumaraswamy_distribution) is usually defined to be a two parameter family of distributions. But on p117 it depends on (a,s,gamma,beta)

**Comment by gecrooks** [comment]
My general policy is to include location and scale parameters unless there is a compelling reason not to (e.g. chi-square). 

So should be 
`Dagum(x; a,s gamma, beta) = GenBetaPrime(x;a,s,1,gamma,-beta)`,
 and 
`LogLogistic(a,s,beta) = GenBetaPrime(a,s,1,1,beta)`

Kumaraswamy is as intended.

Table 18.1 needs updating too.

**Comment by gecrooks** [comment]
Fixed
